### PR TITLE
Update ReadDeviceToCloudMessages.js

### PR DESCRIPTION
**Pull request by amarzavery**

### CODE REVIEW

**Comment by pierreca** [comment]
Please add a note somewhere that the minimum node runtime required is Node v8.x.x

**Comment by amarzavery** [comment]
@pierreca - I am working on a PR that down compiles the generated code to es2015 target. Please review the changes [here](https://github.com/Azure/azure-event-hubs-node/pull/158/commits/55967e0a61ca5202730bb7f82d541b720bc1a817). This should support node.js version 6.x and above. Will not be supporting 4.x.

**Comment by amarzavery** [comment]
@pierreca - Please review and merge the PR, if everything looks good. 1.0.3 version of @azure/event-hubs node supports node.js version 6.x and above.

**Comment by pierreca** [comment]
@amarzavery I can approve but i can't merge i don't own this repo... :shipit:

**Comment by amarzavery** [comment]
@gk-8 - Seems like you have contributed to this repo and you should have merge rights. Can you please merge this PR? This PR ensures that the sample uses the latest version of the SDK.

**Comment by gk-8** [comment]
Merged to master branch, thanks!

**Pull request merged**
